// Mock data for portfolios and candidates
export const portfoliosData = [
  {
    id: "student-council-president",
    title: "Student Council President",
    description: "Lead the student body and represent student interests",
    candidates: [
      {
        id: "sarah-johnson",
        firstName: "Sarah",
        lastName: "Johnson",
        image: "/placeholder.svg?height=120&width=120",
        bio: "Experienced leader with a passion for student advocacy and positive change.",
      },
      {
        id: "michael-chen",
        firstName: "Michael",
        lastName: "Chen",
        image: "/placeholder.svg?height=120&width=120",
        bio: "Dedicated to improving school facilities and student life experiences.",
      },
      {
        id: "emma-williams",
        firstName: "Emma",
        lastName: "Williams",
        image: "/placeholder.svg?height=120&width=120",
        bio: "Committed to fostering inclusivity and academic excellence for all students.",
      },
    ],
  },
  {
    id: "sports-captain",
    title: "Sports Captain",
    description: "Organize and lead school sports activities and competitions",
    candidates: [
      {
        id: "david-rodriguez",
        firstName: "David",
        lastName: "Rodriguez",
        image: "/placeholder.svg?height=120&width=120",
        bio: "Varsity athlete with strong leadership skills and team spirit.",
      },
      {
        id: "lisa-thompson",
        firstName: "Lisa",
        lastName: "Thompson",
        image: "/placeholder.svg?height=120&width=120",
        bio: "Multi-sport athlete dedicated to promoting fitness and teamwork.",
      },
    ],
  },
  {
    id: "head-boy-girl",
    title: "Head Boy/Girl",
    description: "Represent the school at official events and ceremonies",
    candidates: [
      {
        id: "alex-parker",
        firstName: "Alex",
        lastName: "Parker",
        image: "/placeholder.svg?height=120&width=120",
        bio: "Outstanding academic record with excellent communication skills.",
      },
      {
        id: "jordan-smith",
        firstName: "Jordan",
        lastName: "Smith",
        image: "/placeholder.svg?height=120&width=120",
        bio: "Natural leader with a strong commitment to school values and traditions.",
      },
    ],
  },
  {
    id: "secretary",
    title: "Secretary",
    description: "Maintain records and coordinate student council meetings",
    candidates: [
      {
        id: "maya-patel",
        firstName: "Maya",
        lastName: "Patel",
        image: "/placeholder.svg?height=120&width=120",
        bio: "Highly organized with excellent attention to detail and communication skills.",
      },
      {
        id: "james-wilson",
        firstName: "James",
        lastName: "Wilson",
        image: "/placeholder.svg?height=120&width=120",
        bio: "Reliable and efficient with strong administrative and organizational abilities.",
      },
    ],
  },
];

export const PINS = [
  "QPK6A",
  "KEGMX",
  "ICXUF",
  "4SYJ5",
  "WIAL3",
  "0SULR",
  "168LZ",
  "J3Y4O",
  "0DGH9",
  "1HORZ",
  "W4IV6",
  "U1UJE",
  "BGLWA",
  "S2CP6",
  "NFX5H",
  "LJ3ZC",
  "K5YOC",
  "TDL8D",
  "69VF4",
  "JIVD2",
  "LT6B5",
  "4TJ1X",
  "WSD6E",
  "BX1UT",
  "JLP9V",
  "0H2NA",
  "8WOP9",
  "XFJUZ",
  "UJMFQ",
  "7FJYM",
  "IM4T6",
  "4KFCB",
  "NSRUS",
  "MM2PK",
  "2GG8K",
  "0CCA1",
  "7BOR6",
  "TLGPV",
  "0AUDQ",
  "Z817C",
  "AIXK0",
  "FBGJN",
  "GMHKA",
  "WMZFY",
  "IIHM9",
  "1OWC8",
  "QADSZ",
  "KCQM3",
  "R7TS2",
  "T03CV",
  "XM4Z0",
  "UDLSC",
  "HP1HH",
  "W4NH6",
  "1GUJR",
  "BRAQQ",
  "WS05S",
  "RZUL8",
  "EKRE7",
  "ESO2J",
  "3YGB1",
  "JPYQW",
  "M99VX",
  "3RZTO",
  "3JHMS",
  "YPDLC",
  "9K916",
  "XMGSJ",
  "JTAFR",
  "1HD8R",
  "42UYA",
  "LOXGO",
  "OIYCK",
  "F81OD",
  "7A5LF",
  "OWG9R",
  "D7RCS",
  "3CSCX",
  "G9RJW",
  "QQJJ2",
  "66ZS5",
  "45NS0",
  "GFG17",
  "GZBZF",
  "EBYXK",
  "EG1PJ",
  "UJVY8",
  "QA0GQ",
  "LWI6P",
  "IGF4I",
  "0GDPY",
  "G0NAP",
  "DZ40Y",
  "9A62O",
  "1BLVB",
  "HY49G",
  "YEGYC",
  "FSKEJ",
  "GH67G",
  "DAVTB",
  "CSZBQ",
  "PGMJ0",
  "4K6JZ",
  "RZBWV",
  "RQQKY",
  "YC6R7",
  "H0IGW",
  "OU756",
  "28DG7",
  "28MZZ",
  "YA10O",
  "N4IXL",
  "RM23Q",
  "Z836V",
  "T9HCB",
  "RGFPR",
  "BXEZU",
  "P5HXD",
  "MNXLQ",
  "AGEQ8",
  "XRGUX",
  "RJIRG",
  "W0G52",
  "CC1N9",
  "GRVKT",
  "TUVXA",
  "3TOYS",
  "5IQQN",
  "CAN2D",
  "QOZYJ",
  "ABVBD",
  "A1E8A",
  "KKTT2",
  "FZ3OK",
  "D3OXM",
  "46ZJB",
  "M76GR",
  "UPEMV",
  "7HXJY",
  "LA5ZU",
  "40LJH",
  "UBHF1",
  "UBBCF",
  "OUU92",
  "2CSTQ",
  "TYWVE",
  "WPYO8",
  "TJ30W",
  "1UAC9",
  "S9OB9",
  "UOV97",
  "VHTLQ",
  "7DVK7",
  "CQV5Z",
  "9K7OW",
  "2SCRP",
  "51LLT",
  "07V6J",
  "4E1GR",
  "P6ZNG",
  "J8U2U",
  "EP9Z1",
  "TOA6O",
  "GW6OV",
  "8J6IR",
  "J4N1B",
  "XF2AX",
  "EIA2I",
  "TIM5S",
  "KUWAK",
  "8W4RA",
  "X4LSO",
  "848OC",
  "3BCXG",
  "AAQGK",
  "ZDCO3",
  "BDI94",
  "BTHW4",
  "DH0R0",
  "2VIKZ",
  "S5F62",
  "WBA00",
  "RA0I0",
  "TBHDD",
  "MX1YI",
  "JPMUX",
  "0UESY",
  "B3B7O",
  "XTU35",
  "VNHKQ",
  "3AI4Z",
  "Z2QXI",
  "X1RI1",
  "FJTBD",
  "JGPKS",
  "F7QHT",
  "59IGM",
  "3TZ0Y",
  "LBV6J",
  "VD8SR",
  "BFY6E",
  "S8DWV",
  "HR8BE",
  "XRGQC",
  "ROIEF",
  "6XK3B",
  "Y32QO",
  "5HC6N",
  "RQEEY",
  "A4BZC",
  "YIPP9",
  "NXKBI",
  "5NOQO",
  "T6O1V",
  "O377K",
  "UL917",
  "P5WM9",
  "SBQEL",
  "9AWKT",
  "3IKVP",
  "YHTC3",
  "Q27RK",
  "7F4UJ",
  "5HJH7",
  "FVA68",
  "YKVDA",
  "EDOQR",
  "CKMNA",
  "9ZJ33",
  "TCD83",
  "8R8XO",
  "ALMKN",
  "036IC",
  "LW5YR",
  "YA3UJ",
  "1IS9B",
  "N8HFC",
  "AFDAO",
  "ENW8F",
  "8GJWJ",
  "3H2BR",
  "HRV53",
  "G1ULW",
  "YG6SL",
  "Q2BNE",
  "WGMIB",
  "48XCC",
  "OM2YG",
  "JYJEO",
  "BMMOI",
  "BS5WQ",
  "UW8Y8",
  "YPAA5",
  "0S1R0",
  "NJ2K1",
  "NHE4O",
  "ON0JS",
  "QQ55X",
  "J4269",
  "DWPUC",
  "L3WIJ",
  "VIWLG",
  "FVE83",
  "Y3W4M",
  "SJWWK",
  "7QLEO",
  "G4NWY",
  "W5FN1",
  "Z6N8P",
  "Z9B7M",
  "0T1G4",
  "SD95N",
  "Z4I19",
  "XELGF",
  "DKPG6",
  "V6YS8",
  "0KOVC",
  "HGMTH",
  "OV06S",
  "34NGL",
  "7W1V0",
  "8AZU3",
  "ARH9T",
  "86MIT",
  "52T8W",
  "HDGEB",
  "C0MDR",
  "LBFGG",
  "BOUFH",
  "RNABI",
  "HNAOE",
  "9BBIS",
  "MSIE3",
  "3KUPN",
  "HLWWY",
  "ARIT7",
  "4A7ZA",
  "FIQH7",
  "R9WY4",
  "028MJ",
  "E0IGR",
  "OWQCQ",
  "50MTB",
  "6V0GG",
  "05EJS",
  "EC3YA",
  "73C0Z",
  "PMZGV",
  "FJMYF",
  "JG13G",
  "8J70I",
  "JT22I",
  "8GCQY",
  "2F8UF",
  "8705X",
  "YDF2G",
  "YO1S7",
  "TIC0H",
  "FBQSV",
  "6JDEB",
  "JFDMC",
  "IEZ2G",
  "JXG1O",
  "MQFVC",
  "8FMC2",
  "J715G",
  "L15OT",
  "LN5UW",
  "2SG9H",
  "9DAHV",
  "GPOUT",
  "DDARV",
  "N5ICX",
  "O4B3Z",
  "TR5LI",
  "I58TR",
  "VJ6PR",
  "6K4NK",
  "PLKS3",
  "1V48B",
  "9GO5D",
  "JL3U5",
  "Q4W2B",
  "ZHAFP",
  "711IE",
  "64XLP",
  "55JXP",
  "VQMIU",
  "Z6MZX",
  "MEP2Y",
  "Z649A",
  "ANPJB",
  "9KPPJ",
  "RXQ8B",
  "6SGQ9",
  "YUD51",
  "GYV55",
  "T2Q7T",
  "LE5F6",
  "RRJP4",
  "BZPKO",
  "0TY3A",
  "IT6WH",
  "ZHLM9",
  "2AKON",
  "HGPHX",
  "O4KYF",
  "USOS1",
  "KU9M7",
  "7JJM2",
  "HC7QM",
  "M5TZS",
  "MJ4VF",
  "8SHVB",
  "7UM8V",
  "IKGPA",
  "8T2IB",
  "WVVGF",
  "M5GEE",
  "DAQ4X",
  "K737C",
  "ZE94V",
  "CCVPU",
  "AR0EE",
  "EJHID",
  "UEXN3",
  "CCG20",
  "V8ELW",
  "MH7AZ",
  "4JMOG",
  "HWPF9",
  "F1HAC",
  "SPGKW",
  "Z8RM8",
  "HBM7G",
  "0YLJN",
  "E1UAJ",
  "YJWV2",
  "LEY8I",
  "CZU1H",
  "AQSGO",
  "WW5NA",
  "KHXAQ",
  "CH4D1",
  "CD2D6",
  "J2KYV",
  "29LG9",
  "MT85H",
  "WHJT2",
  "G3S9H",
  "9MWNF",
  "GE48U",
  "ZBC40",
  "NMR3R",
  "MR51F",
  "J0KMK",
  "CNEFA",
  "KZSD6",
  "5CKCF",
  "71QZD",
  "XMOFT",
  "GW9J2",
  "4D3UH",
  "2ZNRU",
  "8B2I1",
  "MJSSS",
  "IETOV",
  "0I1FJ",
  "JV6BS",
  "JU8O1",
  "9MG44",
  "0D203",
  "NE9E7",
  "IDMG3",
  "D2OSB",
  "I91AA",
  "02V6B",
  "4ON69",
  "V3D2G",
  "AJOCK",
  "LBX3O",
  "9YZGS",
  "FLA43",
  "V3T80",
  "DKOOP",
  "4T2FZ",
  "OW24Y",
  "CO1J6",
  "MEY1B",
  "95IB3",
];
